# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ffd1b7b41473321f9f4c4535551751f397b15034098093cc1c5c835a12b96de713896153e48218ade35f83c423cfad8d458a4065543fc765a46c57b53afb1d2

test:
  secret_key_base: d3541f3e4941dd9e3e4121ada51825dce761995677e8422874ac4d88279256f255d2cdd293da3ebe96d6b9cb12615de363408704b6cb0931e099d585e104931c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
